"""add snapshot status

Revision ID: 01c44566d655
Revises: d8e6a8607c10
Create Date: 2026-09-04 23:03:26.967571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c44566d655'
down_revision = 'd8e6a8607c10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is needed here (even though the model only declares a
    # Python-side default) so this ALTER doesn't fail against a table that
    # already has rows.
    op.add_column(
        'snapshot',
        sa.Column('status', sa.String(), nullable=False, server_default='live'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot', 'status')
    # ### end Alembic commands ###
