"""add news_item table

Revision ID: c14df8b4b881
Revises: 01c44566d655
Create Date: 2026-09-04 23:28:04.324276

"""
from alembic import op
import sqlalchemy as sa

from app.vector_type import EmbeddingType


# revision identifiers, used by Alembic.
revision = 'c14df8b4b881'
down_revision = '01c44566d655'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector only exists on Postgres — this migration also runs against
    # the project's default SQLite database (see app/vector_type.py), where
    # there's no such extension and nothing to create.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=True),
    sa.Column('sector_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('embedding', EmbeddingType(), nullable=True),
    sa.Column('dedupe_cluster_id', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_item_instrument_id'), 'news_item', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_news_item_published_at'), 'news_item', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_item_sector_id'), 'news_item', ['sector_id'], unique=False)
    op.create_index(op.f('ix_news_item_url'), 'news_item', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_item_url'), table_name='news_item')
    op.drop_index(op.f('ix_news_item_sector_id'), table_name='news_item')
    op.drop_index(op.f('ix_news_item_published_at'), table_name='news_item')
    op.drop_index(op.f('ix_news_item_instrument_id'), table_name='news_item')
    op.drop_table('news_item')
    # ### end Alembic commands ###
    # pgvector's extension is intentionally left in place on downgrade —
    # dropping a shared Postgres extension from one migration's downgrade
    # risks breaking other tables/databases relying on it.
