"""initial schema

Revision ID: d8e6a8607c10
Revises: 
Create Date: 2026-09-04 22:51:21.755884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e6a8607c10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('corporate_action_history', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=True)
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('adaptive_threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_instrument_id'), 'alert', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_alert_user_id'), 'alert', ['user_id'], unique=False)
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('ratios', sa.JSON(), nullable=True),
    sa.Column('top_headlines', sa.JSON(), nullable=True),
    sa.Column('corporate_action', sa.JSON(), nullable=True),
    sa.Column('earnings_date', sa.Date(), nullable=True),
    sa.Column('rating_change', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_captured_at'), 'snapshot', ['captured_at'], unique=False)
    op.create_index(op.f('ix_snapshot_instrument_id'), 'snapshot', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_snapshot_user_id'), 'snapshot', ['user_id'], unique=False)
    op.create_table('subscription_window',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_window_instrument_id'), 'subscription_window', ['instrument_id'], unique=True)
    op.create_table('watchlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_item_instrument_id'), 'watchlist_item', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_watchlist_item_user_id'), 'watchlist_item', ['user_id'], unique=False)
    op.create_table('diff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('snapshot_before_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_after_id', sa.Integer(), nullable=False),
    sa.Column('before_price', sa.Float(), nullable=False),
    sa.Column('after_price', sa.Float(), nullable=False),
    sa.Column('price_delta_pct', sa.Float(), nullable=False),
    sa.Column('before_volume', sa.Integer(), nullable=True),
    sa.Column('after_volume', sa.Integer(), nullable=True),
    sa.Column('volume_delta_pct', sa.Float(), nullable=True),
    sa.Column('ratio_deltas', sa.JSON(), nullable=False),
    sa.Column('news_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['snapshot_after_id'], ['snapshot.id'], ),
    sa.ForeignKeyConstraint(['snapshot_before_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diff_instrument_id'), 'diff', ['instrument_id'], unique=False)
    op.create_table('significance_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diff_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diff_id'], ['diff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_significance_score_diff_id'), 'significance_score', ['diff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_significance_score_diff_id'), table_name='significance_score')
    op.drop_table('significance_score')
    op.drop_index(op.f('ix_diff_instrument_id'), table_name='diff')
    op.drop_table('diff')
    op.drop_index(op.f('ix_watchlist_item_user_id'), table_name='watchlist_item')
    op.drop_index(op.f('ix_watchlist_item_instrument_id'), table_name='watchlist_item')
    op.drop_table('watchlist_item')
    op.drop_index(op.f('ix_subscription_window_instrument_id'), table_name='subscription_window')
    op.drop_table('subscription_window')
    op.drop_index(op.f('ix_snapshot_user_id'), table_name='snapshot')
    op.drop_index(op.f('ix_snapshot_instrument_id'), table_name='snapshot')
    op.drop_index(op.f('ix_snapshot_captured_at'), table_name='snapshot')
    op.drop_table('snapshot')
    op.drop_index(op.f('ix_alert_user_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_instrument_id'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.drop_table('user')
    op.drop_table('instrument')
    # ### end Alembic commands ###
